micronaut:
  application:
    name: versionAnnotationBug2
datasources:
  default:
    url: jdbc:oracle:thin:@localhost:1521/xe
    driverClassName: oracle.jdbc.OracleDriver
    username: system
    password: oracle
    schema-generate: CREATE_DROP
    dialect: ORACLE

liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'