micronaut:
  application:
    name: versionAnnotationBug2
datasources:
  default:
    url: jdbc:mysql://localhost:3306/dummy?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driverClassName: com.mysql.cj.jdbc.Driver
    username: user
    password: pass
    schema-generate: CREATE_DROP
    dialect: MYSQL

liquibase:
  datasources:
    default:
      change-log: 'classpath:db/liquibase-changelog.xml'